#!/usr/bin/env bash
#Prints "To infinity and beyond" indefinitely with
#a sleep 2 in between each iteration.
#  Displays "I am invincible!!!" in netween each iteration.

while true
do
 echo "To infinity and beyond"
 sleep 2
 trap 'echo "I am invincible!!!"' SIGTERM
done
