#!/usr/bin/env bash
# Loops from to 10 and prints:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

data=0

while [ $data -lt 10 ]
do
 if [ $data -eq 3 ]
 then
   echo "bad luck"
 elif [ $data -eq 7 ]
 then
   echo "good luck"
 else
   echo "Best School"
 fi
 (( data++ ))
done
