#!/usr/bin/env bash
# Prints numbers from 1 to 20 in addition t0:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration

data=1

while [ $data -le 20 ]
do
 echo "$data"
 case $data in
   "4") echo "bad luck from China";;
   "9") echo "bad luck from Japan";;
   "17") echo "bad luck from Italy";;
 esac
 (( data++ ))
done
